// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: api/proto/auth.proto

package authv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletAddress string                 `protobuf:"bytes,1,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_api_proto_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_proto_rawDescGZIP(), []int{0}
}

func (x *GetStatusRequest) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

type GetStatusResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Status          string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`                                          // ACTIVE, BLOCKED, REVIEW
	TrustScore      int32                  `protobuf:"varint,2,opt,name=trust_score,json=trustScore,proto3" json:"trust_score,omitempty"`               // 0-100
	UpdatedAt       int64                  `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`                  // Unix timestamp
	ContractAddress string                 `protobuf:"bytes,4,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"` // Smart contract address
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_api_proto_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_proto_rawDescGZIP(), []int{1}
}

func (x *GetStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetStatusResponse) GetTrustScore() int32 {
	if x != nil {
		return x.TrustScore
	}
	return 0
}

func (x *GetStatusResponse) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *GetStatusResponse) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

type SetStatusRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WalletAddress  string                 `protobuf:"bytes,1,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	TrustScore     int32                  `protobuf:"varint,3,opt,name=trust_score,json=trustScore,proto3" json:"trust_score,omitempty"`
	AdminSignature string                 `protobuf:"bytes,4,opt,name=admin_signature,json=adminSignature,proto3" json:"admin_signature,omitempty"` // Admin authorization
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SetStatusRequest) Reset() {
	*x = SetStatusRequest{}
	mi := &file_api_proto_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStatusRequest) ProtoMessage() {}

func (x *SetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStatusRequest.ProtoReflect.Descriptor instead.
func (*SetStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_proto_rawDescGZIP(), []int{2}
}

func (x *SetStatusRequest) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

func (x *SetStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SetStatusRequest) GetTrustScore() int32 {
	if x != nil {
		return x.TrustScore
	}
	return 0
}

func (x *SetStatusRequest) GetAdminSignature() string {
	if x != nil {
		return x.AdminSignature
	}
	return ""
}

type SetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TxHash        string                 `protobuf:"bytes,2,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetStatusResponse) Reset() {
	*x = SetStatusResponse{}
	mi := &file_api_proto_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStatusResponse) ProtoMessage() {}

func (x *SetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStatusResponse.ProtoReflect.Descriptor instead.
func (*SetStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_proto_rawDescGZIP(), []int{3}
}

func (x *SetStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetStatusResponse) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *SetStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type VerifyWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletAddress string                 `protobuf:"bytes,1,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	Signature     string                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyWalletRequest) Reset() {
	*x = VerifyWalletRequest{}
	mi := &file_api_proto_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyWalletRequest) ProtoMessage() {}

func (x *VerifyWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyWalletRequest.ProtoReflect.Descriptor instead.
func (*VerifyWalletRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_proto_rawDescGZIP(), []int{4}
}

func (x *VerifyWalletRequest) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

func (x *VerifyWalletRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *VerifyWalletRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type VerifyWalletResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Verified      bool                   `protobuf:"varint,1,opt,name=verified,proto3" json:"verified,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	TrustScore    int32                  `protobuf:"varint,3,opt,name=trust_score,json=trustScore,proto3" json:"trust_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyWalletResponse) Reset() {
	*x = VerifyWalletResponse{}
	mi := &file_api_proto_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyWalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyWalletResponse) ProtoMessage() {}

func (x *VerifyWalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyWalletResponse.ProtoReflect.Descriptor instead.
func (*VerifyWalletResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_proto_rawDescGZIP(), []int{5}
}

func (x *VerifyWalletResponse) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *VerifyWalletResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *VerifyWalletResponse) GetTrustScore() int32 {
	if x != nil {
		return x.TrustScore
	}
	return 0
}

type BatchGetStatusRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WalletAddresses []string               `protobuf:"bytes,1,rep,name=wallet_addresses,json=walletAddresses,proto3" json:"wallet_addresses,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BatchGetStatusRequest) Reset() {
	*x = BatchGetStatusRequest{}
	mi := &file_api_proto_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetStatusRequest) ProtoMessage() {}

func (x *BatchGetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetStatusRequest.ProtoReflect.Descriptor instead.
func (*BatchGetStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_proto_rawDescGZIP(), []int{6}
}

func (x *BatchGetStatusRequest) GetWalletAddresses() []string {
	if x != nil {
		return x.WalletAddresses
	}
	return nil
}

type BatchGetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statuses      []*GetStatusResponse   `protobuf:"bytes,1,rep,name=statuses,proto3" json:"statuses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetStatusResponse) Reset() {
	*x = BatchGetStatusResponse{}
	mi := &file_api_proto_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetStatusResponse) ProtoMessage() {}

func (x *BatchGetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetStatusResponse.ProtoReflect.Descriptor instead.
func (*BatchGetStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_proto_rawDescGZIP(), []int{7}
}

func (x *BatchGetStatusResponse) GetStatuses() []*GetStatusResponse {
	if x != nil {
		return x.Statuses
	}
	return nil
}

var File_api_proto_auth_proto protoreflect.FileDescriptor

const file_api_proto_auth_proto_rawDesc = "" +
	"\n" +
	"\x14api/proto/auth.proto\x12\aauth.v1\"9\n" +
	"\x10GetStatusRequest\x12%\n" +
	"\x0ewallet_address\x18\x01 \x01(\tR\rwalletAddress\"\x96\x01\n" +
	"\x11GetStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1f\n" +
	"\vtrust_score\x18\x02 \x01(\x05R\n" +
	"trustScore\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\x03R\tupdatedAt\x12)\n" +
	"\x10contract_address\x18\x04 \x01(\tR\x0fcontractAddress\"\x9b\x01\n" +
	"\x10SetStatusRequest\x12%\n" +
	"\x0ewallet_address\x18\x01 \x01(\tR\rwalletAddress\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1f\n" +
	"\vtrust_score\x18\x03 \x01(\x05R\n" +
	"trustScore\x12'\n" +
	"\x0fadmin_signature\x18\x04 \x01(\tR\x0eadminSignature\"`\n" +
	"\x11SetStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x17\n" +
	"\atx_hash\x18\x02 \x01(\tR\x06txHash\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"t\n" +
	"\x13VerifyWalletRequest\x12%\n" +
	"\x0ewallet_address\x18\x01 \x01(\tR\rwalletAddress\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\tR\tsignature\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"k\n" +
	"\x14VerifyWalletResponse\x12\x1a\n" +
	"\bverified\x18\x01 \x01(\bR\bverified\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1f\n" +
	"\vtrust_score\x18\x03 \x01(\x05R\n" +
	"trustScore\"B\n" +
	"\x15BatchGetStatusRequest\x12)\n" +
	"\x10wallet_addresses\x18\x01 \x03(\tR\x0fwalletAddresses\"P\n" +
	"\x16BatchGetStatusResponse\x126\n" +
	"\bstatuses\x18\x01 \x03(\v2\x1a.auth.v1.GetStatusResponseR\bstatuses2\xb5\x02\n" +
	"\vAuthService\x12B\n" +
	"\tGetStatus\x12\x19.auth.v1.GetStatusRequest\x1a\x1a.auth.v1.GetStatusResponse\x12B\n" +
	"\tSetStatus\x12\x19.auth.v1.SetStatusRequest\x1a\x1a.auth.v1.SetStatusResponse\x12K\n" +
	"\fVerifyWallet\x12\x1c.auth.v1.VerifyWalletRequest\x1a\x1d.auth.v1.VerifyWalletResponse\x12Q\n" +
	"\x0eBatchGetStatus\x12\x1e.auth.v1.BatchGetStatusRequest\x1a\x1f.auth.v1.BatchGetStatusResponseB.Z,qubic-microauth/api/proto/gen/auth/v1;authv1b\x06proto3"

var (
	file_api_proto_auth_proto_rawDescOnce sync.Once
	file_api_proto_auth_proto_rawDescData []byte
)

func file_api_proto_auth_proto_rawDescGZIP() []byte {
	file_api_proto_auth_proto_rawDescOnce.Do(func() {
		file_api_proto_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_auth_proto_rawDesc), len(file_api_proto_auth_proto_rawDesc)))
	})
	return file_api_proto_auth_proto_rawDescData
}

var file_api_proto_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_proto_auth_proto_goTypes = []any{
	(*GetStatusRequest)(nil),       // 0: auth.v1.GetStatusRequest
	(*GetStatusResponse)(nil),      // 1: auth.v1.GetStatusResponse
	(*SetStatusRequest)(nil),       // 2: auth.v1.SetStatusRequest
	(*SetStatusResponse)(nil),      // 3: auth.v1.SetStatusResponse
	(*VerifyWalletRequest)(nil),    // 4: auth.v1.VerifyWalletRequest
	(*VerifyWalletResponse)(nil),   // 5: auth.v1.VerifyWalletResponse
	(*BatchGetStatusRequest)(nil),  // 6: auth.v1.BatchGetStatusRequest
	(*BatchGetStatusResponse)(nil), // 7: auth.v1.BatchGetStatusResponse
}
var file_api_proto_auth_proto_depIdxs = []int32{
	1, // 0: auth.v1.BatchGetStatusResponse.statuses:type_name -> auth.v1.GetStatusResponse
	0, // 1: auth.v1.AuthService.GetStatus:input_type -> auth.v1.GetStatusRequest
	2, // 2: auth.v1.AuthService.SetStatus:input_type -> auth.v1.SetStatusRequest
	4, // 3: auth.v1.AuthService.VerifyWallet:input_type -> auth.v1.VerifyWalletRequest
	6, // 4: auth.v1.AuthService.BatchGetStatus:input_type -> auth.v1.BatchGetStatusRequest
	1, // 5: auth.v1.AuthService.GetStatus:output_type -> auth.v1.GetStatusResponse
	3, // 6: auth.v1.AuthService.SetStatus:output_type -> auth.v1.SetStatusResponse
	5, // 7: auth.v1.AuthService.VerifyWallet:output_type -> auth.v1.VerifyWalletResponse
	7, // 8: auth.v1.AuthService.BatchGetStatus:output_type -> auth.v1.BatchGetStatusResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_auth_proto_init() }
func file_api_proto_auth_proto_init() {
	if File_api_proto_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_auth_proto_rawDesc), len(file_api_proto_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_auth_proto_goTypes,
		DependencyIndexes: file_api_proto_auth_proto_depIdxs,
		MessageInfos:      file_api_proto_auth_proto_msgTypes,
	}.Build()
	File_api_proto_auth_proto = out.File
	file_api_proto_auth_proto_goTypes = nil
	file_api_proto_auth_proto_depIdxs = nil
}
